### ISSUE TITLE
Просьба добавить лицензию

### ISSUE THREAD

**Issue by LevkinSergey** [oNikolaev/navigator#1]

**Comment by oNikolaev** [comment]
Добрый день. О какой лицензии идет речь? Разработка абсолютно бесплатна. На инфостарте платная скачка только собранной версии.

**Comment by LevkinSergey** [comment]
на гитхабе есть разработки, у которых код открыт, а использовать можно только приобретя лицензию. Плюс может вы против включения разработки в платные продукты и т.п.
Лицензия позволяет понять, в каких случаях код можно использовать.

Обычно в репозитории добавляется файл LICENSE. И в нем указываются условия использования. 

Я наконец вернулся к вопросу использования вашей разработки в https://github.com/cpr1c/tools_ui_1c.
Вы уже давали разрешение на инфостарте.

**Comment by oNikolaev** [comment]
Да, без проблем. А где-то есть готовый файл лицензии?

**Comment by LevkinSergey** [comment]
Нашел такой маршрут. Раньше было в настройках репозитория закладка "Community"

![image](https://user-images.githubusercontent.com/36307272/118665627-1dd36680-b7fb-11eb-9fc0-39a9ccfaece1.png)
![image](https://user-images.githubusercontent.com/36307272/118665699-2cba1900-b7fb-11eb-94ca-ee59f394544d.png)

**Comment by LevkinSergey** [comment]
И дальше откроется закладка где можно выбрать и закоммитить в репозиторий
