### ISSUE TITLE
Просьба опубликовать релиз в виде cf

### ISSUE THREAD

**Issue by shalimski** [oNikolaev/navigator#2]

**Comment by oNikolaev** [comment]
Добрый день. А зачем? Обработка открывается в любой базе. Хоть типовой, хоть не типовой.

**Comment by shalimski** [comment]
Не заметил что это именно обработка, всегда ожидаешь видеть в разделе releases обработку/конфигурацию в собранном виде. Это удобнее чем самому собирать и позволяет зафиксировать версию

**Comment by oNikolaev** [comment]
Собранная (файл - сохранить как - epf) на инфостарте. Ок, сделаю.
